Shader "Custom/PerspectiveWarp"
{
    //This shader generated by Gemini
    //while I understand perspective warping, HLSL syntax was easier to verify than learn from scratch for the purposes of this activity
    Properties
    {
        _MainTex ("Camera Texture", 2D) = "white" {}
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "RenderPipeline"="UniversalPipeline" }
        Pass
        {
            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            struct Attributes {
                float4 positionOS : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct Varyings {
                float4 positionCS : SV_POSITION;
                float2 uv : TEXCOORD0;
            };

            TEXTURE2D(_MainTex);
            SAMPLER(sampler_MainTex);
            
            // These are the 4 viewport points we pass from C#
            float4 _Corners[4]; 

            Varyings vert(Attributes input) {
                Varyings output;
                output.positionCS = TransformObjectToHClip(input.positionOS.xyz);
                output.uv = input.uv;
                return output;
            }

            half4 frag(Varyings input) : SV_Target {
                // Bilinear interpolation between the 4 captured screen points
                // based on the current quad's local UVs
                float2 top = lerp(_Corners[0].xy, _Corners[1].xy, input.uv.x);
                float2 bottom = lerp(_Corners[3].xy, _Corners[2].xy, input.uv.x);
                float2 targetUV = lerp(top, bottom, 1.0 - input.uv.y);

                return SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, targetUV);
            }
            ENDHLSL
        }
    }
}